### PR TITLE
(maint) remove i18n plumbing and dependency on gettext-setup

### PR DESCRIPTION
**Pull request by eputnam**
This started when GettextSetup was removed from Puppet. Now we've been seeing issues where semantic_puppet has been sneaking GettextSetup.initialize into runtime environments where Puppet is now doing its own thing. Since sematnic_puppet doesn't actually have any translations to use in the first place, the easiest solution seems to be to rip all of this stuff out until such a time when it is actually needed.

### CODE REVIEW

**Comment by joshcooper** [comment]
ping @scotje @thallgren

**Comment by scotje** [comment]
Do any of the SemanticPuppet exceptions bubble up into runtime error messages from `puppet`? (I feel like the probably do.) If so, do we care if those messages aren't able to be localized? Or can they be captured and re-thrown by `puppet` so that they can be localized there?

**Comment by joshcooper** [comment]
So the funny thing (it's actually not funny) is that puppet already has a vendored version of `semantic_puppet`. It is in a similar state where it has a `config.yaml` but no `*.po` files. I did a quick look at puppet, and it seems to mostly catch SemanticPuppet validation errors and re-raise the appropriate localized exception. I don't know if it's 100% coverage That said, this PR doesn't change anything except make it less likely for `GettextSetup.initialize` to be called multiple times.

**Comment by scotje** [comment]
Yeah, the never-ending saga of semantic_puppet vendoring. 😞 

Sounds like there is no reason to not rip this out then.

**Comment by scotje** [comment]
Need to amend the README to remove the i18n instructions, planning to do that tomorrow and merge this.

**Pull request merged**
