### PR TITLE
Add Ruby 3.0 testing

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by skywalkerz0r** [comment]
Hi. Most of the current tests aren't compatible with ruby 3.0, correct?

**Comment by GabrielNagy** [comment]
Thanks for the contribution!

We're not sure how we'll handle SortedSet being extracted to a separate gem. 

For puppet we decided to use `Puppet::RbTreeMap` instead to avoid adding another gem dependency (https://github.com/puppetlabs/puppet/pull/8589), but we can't do that here since this gem doesn't pull puppet. This might have to wait until the next puppet release.

**Comment by bastelfreak** [comment]
I'm happy with any solution, as long as it works. Sadly I don't know enough to properly fix the tests. My goal is to package Puppet on Arch Linux build against Ruby 3.0.1.

**Comment by gimmyxd** [comment]
Closed in favour of #38

**Pull request closed without merging**
